kind: Deployment
apiVersion: apps/v1 
metadata:
  namespace: molesdk 
  name: sdk-admin
  labels:
    app: sdk-admin
spec:
  selector:
    matchLabels:
      app: sdk-admin
  replicas: 1
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: 1 
      maxUnavailable: 0
  template: 
    metadata: 
      labels:
        app: sdk-admin
    spec:
      containers:
        - name: molesdk-administrator
          image: msfdocker/myproject:molesdk-admin
          ports: 
            - containerPort: 80 
---
kind: Service
apiVersion: v1
metadata:
  namespace: molesdk
  name: sdkadmin-service
  labels:
    app: sdk-admin
spec:
  selector:
    app: sdk-admin
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
